"""index jobs.source_name

Revision ID: 2b2db25c4e05
Revises: caefde5d12b0
Create Date: 2026-10-07 14:53:14.031688

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2b2db25c4e05'
down_revision = 'caefde5d12b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_source_name'), ['source_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_source_name'))

    # ### end Alembic commands ###
