"""add jobs.raw_hash

Revision ID: 3e6168376086
Revises: 2b2db25c4e05
Create Date: 2026-10-07 15:28:52.075276

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3e6168376086'
down_revision = '2b2db25c4e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('raw_hash')

    # ### end Alembic commands ###
