"""initial schema

Revision ID: caefde5d12b0
Revises: 
Create Date: 2026-08-05 16:13:50.551694

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'caefde5d12b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.Column('career_urls', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('closed_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_runs_started_at'), ['started_at'], unique=False)

    op.create_table('source_state',
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=300), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('failure_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_adapter', sa.String(length=50), nullable=False),
    sa.Column('source_job_id', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('team', sa.String(length=200), nullable=True),
    sa.Column('primary_location', sa.String(length=300), nullable=True),
    sa.Column('all_locations', sa.JSON(), nullable=False),
    sa.Column('remote_type', sa.String(length=20), nullable=False),
    sa.Column('country_codes', sa.JSON(), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('role_family', sa.String(length=50), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('start_date_min', sa.Date(), nullable=True),
    sa.Column('start_date_max', sa.Date(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('full_time_required', sa.Boolean(), nullable=True),
    sa.Column('degree_levels', sa.JSON(), nullable=False),
    sa.Column('graduation_min', sa.Date(), nullable=True),
    sa.Column('graduation_max', sa.Date(), nullable=True),
    sa.Column('requires_return_to_school', sa.Boolean(), nullable=True),
    sa.Column('work_authorization_text', sa.Text(), nullable=True),
    sa.Column('citizenship_required', sa.Boolean(), nullable=True),
    sa.Column('clearance_required', sa.Boolean(), nullable=True),
    sa.Column('compensation_min', sa.Float(), nullable=True),
    sa.Column('compensation_max', sa.Float(), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('compensation_currency', sa.String(length=10), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('digest_pending', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('score_components', sa.JSON(), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('eligibility_level', sa.String(length=30), nullable=False),
    sa.Column('eligibility_text', sa.Text(), nullable=True),
    sa.Column('season_confidence', sa.Float(), nullable=False),
    sa.Column('eligibility_confidence', sa.Float(), nullable=False),
    sa.Column('is_early_career', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_hash', name='uq_jobs_identity_hash')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_identity_hash'), ['identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_match_score'), ['match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_role_family'), ['role_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('applications',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_variant', sa.String(length=50), nullable=True),
    sa.Column('referral_status', sa.String(length=100), nullable=True),
    sa.Column('referrer_name', sa.String(length=200), nullable=True),
    sa.Column('recruiter_name', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('oa_date', sa.Date(), nullable=True),
    sa.Column('interview_stage', sa.String(length=100), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('job_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('alias_kind', sa.String(length=20), nullable=False),
    sa.Column('alias_hash', sa.String(length=64), nullable=False),
    sa.Column('source_adapter', sa.String(length=50), nullable=True),
    sa.Column('source_job_id', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_kind', 'alias_hash', name='uq_alias_kind_hash')
    )
    with op.batch_alter_table('job_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_aliases_alias_hash'), ['alias_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_aliases_job_id'), ['job_id'], unique=False)

    op.create_table('job_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('meaningful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_changes_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_changes_job_id'))

    op.drop_table('job_changes')
    with op.batch_alter_table('job_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_aliases_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_aliases_alias_hash'))

    op.drop_table('job_aliases')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_season'))
        batch_op.drop_index(batch_op.f('ix_jobs_role_family'))
        batch_op.drop_index(batch_op.f('ix_jobs_match_score'))
        batch_op.drop_index(batch_op.f('ix_jobs_identity_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))

    op.drop_table('jobs')
    op.drop_table('source_state')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_scan_runs_company_id'))

    op.drop_table('scan_runs')
    op.drop_table('meta')
    op.drop_table('companies')
    # ### end Alembic commands ###
