"""add jobs.resume_sent_at

Revision ID: d443ed770624
Revises: 3e6168376086
Create Date: 2026-10-07 23:46:37.874136

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd443ed770624'
down_revision = '3e6168376086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('resume_sent_at')

    # ### end Alembic commands ###
